### ISSUE TITLE
Not working on chaning of view

### ISSUE THREAD

**Issue by cloudzon-hitesh** [pc035860/angular-easyfb#13]
I am using easyfb for my angularjs app but it work fine on page reload but when i am going to another page then this is not working but when i reload page it's working fine.

I want to use this with two different controller and this controller have their own html view page.

**Comment by vivekrajput300** [comment]
<div class="fb-page" data-href="https://www.facebook.com/rossschool" data-height="{{vm.UserDetails.loggedUser.userTypeId == 2?'401':(vm.UserDetails.loggedUser.userTypeId == 1?'500':'847')}}" data-width="500" data-tabs="timeline" data-small-header="true"
                                data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
                                <blockquote cite="https://www.facebook.com/rossschool" class="fb-xfbml-parse-ignore">
                                    <a href="https://www.facebook.com/rossschool">Facebook</a>
                                </blockquote>
                            </div>

Its working on loading, but when i navigate to another route and come back to this page its coming like this 

![image](https://user-images.githubusercontent.com/22904696/43591193-60acab86-9690-11e8-8797-536bd59ab2fc.png)
 please suggest
