### ISSUE TITLE
Integrating with framework cause "'X-Frame-Options' to 'DENY'."

### ISSUE THREAD

**Issue by steve21124** [pc035860/angular-easyfb#29]
angular-easyfb work really well login and logout. However when I try to integrate with other framework (ionic -- https://github.com/driftyco/ionic) it cause "'X-Frame-Options' to 'DENY'." when "logging out".

Since your library work well can logging out successfully. Can you give me idea, what might be the problem of x-frame deny. (Probably "next" params?)

"https://www.facebook.com/logout.php?access_token=ACCESS_TOKEN&app_id=APPID&channel_url=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2FdgdTycPTSRj.js%3Fversion%3D41%23cb%3Df2e36ae79c%26domain%3Drun.plnkr.co%26origin%3Dhttp%253A%252F%252Frun.plnkr.co%252Ff6eb1eb14%26relation%3Dparent.parent&display=hidden&e2e=%7B%7D&locale=en_US&next=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2FdgdTycPTSRj.js%3Fversion%3D41%23cb%3Df229ffc204%26domain%3Drun.plnkr.co%26origin%3Dhttp%253A%252F%252Frun.plnkr.co%252Ff6eb1eb14%26relation%3Dparent%26frame%3Df523faf0c&sdk=joey"

**Comment by deejbee** [comment]
I know this issue was raised a long time ago but I am seeing it.  It's not logging out of facebook.  Did you find a fix for it?

**Comment by deejbee** [comment]
I just found the answer here [https://stackoverflow.com/questions/22331373/facebook-js-api-cant-logout](url) by SoldierCorp.

You need to make sure the app website is set correctly (mine wasn't)

**Comment by steve21124** [comment]
Great. Thank for the answer.
