### ISSUE TITLE
Can this plugin work with the latest develop branch of the phonegap plugin

### ISSUE THREAD

**Issue by JonathanHindi** [pc035860/angular-easyfb#34]
Hi there, 

Can this plugin work with the latest develop branch of the phonegap plugin as it's a rewrite of the cordova js api? 

Thanks..

**Comment by scripta55** [comment]
hi @JonathanHindi  did you get easyfb to work with phonegap? sharing... i am not able. when i test on chrome everything works. when i build and run on the device the button does not even show up on the screen.. anyone able to help please? thanks in advance @pc035860  :)

**Comment by pc035860** [comment]
Hi @scripta55 ,

I haven't used PhoneGap myself. I'll take a look at it.
It seems that PhoneGap has evolved a lot...

**Comment by JonathanHindi** [comment]
Hey @scripta55, I really don't remember it's about 2 years ago. But I think it didn't work and I used something else, that I can't remember as well.
