### ISSUE TITLE
FB.logout() called without an access token.

### ISSUE THREAD

**Issue by shadowsyntax** [pc035860/angular-easyfb#43]
I keep getting this error when I used the method outlined in your plunker. The thing is that i'm using your solution with Ionic framework but also I am using Firebase for login authentication. I tried using there method for log-out but it doesn't completely log me out of the Facebook API. Thus the reason I'm trying to use yours for complete logout will I keep Firebase for login due some other requirements I have in my app. Thanks.

**Comment by pc035860** [comment]
Hi @shadowsyntax ,

Sorry for the late response.
I'm not familiar with either Ionic or Firebase, but I suggest that you can try wrapping `.logout()` with `.getLoginStatus()`, which might solve the `called without an access token` error.

```js
ezfb.getLoginStatus(function (response) {
  if (response && response.status === 'connected') {
    ezfb.logout();
  }
});
```

The thing is that Facebook JS SDK actually tries to maintain an active access token in it, which seems can only obtained through calling `.getLoginStatus()`.

See also: [FB.logout() called without an access token. javascript sdk](http://stackoverflow.com/questions/19842610/fb-logout-called-without-an-access-token-javascript-sdk)

**Comment by shadowsyntax** [comment]
Hello @pc035860, I tried your trick and it works fine now. My apologies for getting back to you so late, been tackling some other programming issues.

Thanks a lot.

**Comment by dragipostolovski** [comment]
To use the access token with the FB.logout method, you need to ensure that you have obtained the access token during the login process and that it is available when you want to log out the user.

```
FB.logout(function(response) {
                
    if ( 'connected' === response.status ) {
        window.location.href = data.render.logout_url;
    } else {
        console.log( 'There has been an error.' );
    }
}, {
    access_token: data.render.accessToken
});
```
