### ISSUE TITLE
Getting warning: FB.init has already been called - this could indicate a problem

### ISSUE THREAD

**Issue by EvilJohnny** [pc035860/angular-easyfb#50]
Hi,

currently I am only using the plugin to show the Facebook "Like" button, but I am planning on using it for API alls in the future.

Everything seems to work ok with the button, but I am getting the warning: 
```FB.init has already been called - this could indicate a problem```
with the page load.

Any clues why this is happening?

I am using angular 1.3.15

**Comment by pc035860** [comment]
Did you load FB JS SDK yourself by adding this: (which is from [the official doc](https://developers.facebook.com/docs/javascript/quickstart/v2.4))

```html
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : 'your-app-id',
      xfbml      : true,
      version    : 'v2.4'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
```

to the web page?

`angular-easyfb` wraps the SDK loading process into it, so there's no need to load the SDK by yourself. And you can access the SDK loading function with [getLoadSDKFunction / setLoadSDKFunction](https://github.com/pc035860/angular-easyfb#getloadsdkfunction--setloadsdkfunction).

**Comment by EvilJohnny** [comment]
No I didn't... But now that you say it, it is possible that the SDK is already loaded in the project. I am using this in a Meteor project, that includes a package fir facebook login, so I think that package might be loading the SDK before ezfb does it...
Thing is, if I don't call the init on ezfb, I can't use the ezfb like button directive, right? (or it is not a directive?).
Now I have more doubts than before :sweat_smile:

**Comment by EvilJohnny** [comment]
So it seems that is the problem. Somewhere, at some point (I couldn't figure out where or how), the SDK is already loaded in my project. And the FB.Init function called.

What I did is simply set the initfunction like this:

```javascript
var myInitFunction = ['$window', '$rootScope', 'ezfbInitParams', function ($window, $rootScope, ezfbInitParams) {
	//$window.FB.init(ezfbInitParams);
	$rootScope.$broadcast('FB.init');
}];
	
ezfbProvider.setInitFunction(myInitFunction);

Commenting out the initialization line. And that way seems to work, no warning, the like button is loading ok... I hope everything else also works!

Anyways this is not a problem from the plugin, so I am closing this. Thanks for everthing @pc035860 !!

**Comment by EvilJohnny** [comment]
Oh and I also used:

```javascript
// Feasible config if the FB JS SDK script is already loaded
ezfbProvider.setLoadSDKFunction(['ezfbAsyncInit', function (ezfbAsyncInit) {
	ezfbAsyncInit();
}]);
```

For avoid loading the sdk twice. Just leaving this written down here, in the unlikely case someone has the same exact problem :laughing:

**Comment by pc035860** [comment]
I actually forgot that one was in the README  :expressionless:
Thank you! :+1:

**Comment by EvilJohnny** [comment]
Nah, it didn't work. I do need to load the sdk twice. ezfb is trying to initialize stuff before the "other thing" loads the SDK. I tried to make it wait until the SDK is loaded, but then after waiting for it, the angular templates are already parsed, and the "like" button doesn't show.

I'll go with this until I have time to do something else. Thanks again for the plugin!
