### ISSUE TITLE
Comment box data-width="100%" not working

### ISSUE THREAD

**Issue by Fonger** [pc035860/angular-easyfb#53]
According to [Facebook document](https://developers.facebook.com/docs/plugins/comments),
`data-width="100%"` will make the comment box full width of the parent element
I've tested it and it's working with standard Facebook init

However, this is not working on angular-easyfb. The whole comment box is gone
I inspect the element created by FB sdk, and found that the `width` becomes `0`, which causes the comment box invisible.

I've tried other width such as `500px` and `1000px` and it's working.

Plunkr: (Please select `comment` tab)
http://plnkr.co/edit/ZILG9JG9PnzOB9xjuc6q?p=preview

**Comment by pc035860** [comment]
Hi @Fonger ,

Thanks for reporting. I've fixed the issue and it's on `master` now.
Let me know if something wrong. Or I'll make a release later.

**Comment by Fonger** [comment]
@pc035860 Thank you. It's working now. Hope you can update the version on bower as well.

**Comment by pc035860** [comment]
I just pushed a new tag `v1.3.2`. It should be on bower in a minute.
