### ISSUE TITLE
Error: ezfb.getLoginStatus is not a function

### ISSUE THREAD

**Issue by vin-san** [pc035860/angular-easyfb#54]
Hi,

I'm trying to use ezfb and I have this issue
```
Error: ezfb.getLoginStatus is not a function
 ```

the module seems to be correctly initialised in my index.html.
The controller is located in a sub page rooted by ngRoute.

**Config in index.html**

```
        (function() {
        	angular.module('app', ['720kb.socialshare', 'ui.bootstrap', 'gridster', 'ngRoute', 'dndLists', 'ngFileUpload', 'ezfb'])
        		
                .config(['$routeProvider','$locationProvider', function($routeProvider, $locationProvider, ezfbProvider) {

                 	$locationProvider.html5Mode({enabled: true});

    				$routeProvider
    					.when('/12', {
    						templateUrl: 'kit/12/view.html',
    						controller: 'MainCtrl'
    					})
    					.when('/13', {
    						templateUrl: 'kit/13/test.html',
    						controller: 'MainCtrl'
    					})
    					.otherwise({
    						redirectTo: '/12'
    					});
    				}
		
                	ezfbProvider.setInitParams({
    					appId: '1468678883433799',
    					version: 'v2.3'
  					});  

        		])


        		.controller('RootCtrl', function($scope) {
        			$scope.$on('$locationChangeStart', function(e, next, current) {
        				$scope.page = next.split('/').splice(-1);
        				if ($scope.page!=''){
        					$scope.styleUrl = 'kit/' + $scope.page + '/style.css';
        				}
        			});
        		})  

        })();
```

**Controler in kit/12/view.html**

```
.controller('MainCtrl', ['$scope', 'Upload', function($scope, ezfb, Upload) {

ezfb.getLoginStatus(function (res) {
    $scope.loginStatus = res;

    (more || angular.noop)();
  });

  ezfb.api('/me', function (res) {
    $scope.apiMe = res;
  });

…

}
```

I can't find any help about this issue,
Can I get some help ?

Thanks
Vincent

**Comment by pc035860** [comment]
Hi @vnctaing 

It doesn't seem possible to me for `ezfb.getLoginStatus` to be unavailable. Since it should be published when `ezfb` is established as a service.

Can you dump `$log.debug(ezfb)` output in the `MainCtrl` here?

**Comment by vin-san** [comment]
When I try to use
```
.controller('MainCtrl', ['$scope', 'Upload', function($scope, ezfb, Upload, $log) {
$log.debug(ezfb);
```
I got :
`Error: $log is undefined`
…

I used `console.log(ezfb);` instead. Is it ok ?

```
Object { upload: this.upload(), http: this.http(), setDefaults: this.setDefaults(), defaults: Object, version: "7.0.15", dataUrl: d.dataUrl(), registerValidators: f.registerValidators(), validatePattern: f.validatePattern(), validate: f.validate(), imageDimensions: f.imageDimensions(), 4 de plus… }
```
Can't display *4 more…*

**Comment by pc035860** [comment]
Ah..  I see. You are using [inline annotation](https://docs.angularjs.org/guide/di#inline-array-annotation) in `MainCtrl`, but you forgot to add the annotations for `ezfb` and `$log`. And this is why `$log` is also reported undefined.

Modify your `MainCtrl` code to

```js
.controller('MainCtrl', ['$scope', 'ezfb', 'Upload', function($scope, ezfb, Upload) {
```

should work.

I suggest using [ng-annotate](https://github.com/olov/ng-annotate) for automatic annotating.

**Comment by vin-san** [comment]
I tried it before but I got this error :
`Error: [$injector:unpr] Unknown provider: ezfbProvider <- ezfb <- MainCtrl`

(I don't use minifier but I'll definitly use ng-annotate)

My other modules work fine so I assume that the problem come from ezfb… I just don't get it.

**Comment by vnctaing** [comment]
Have you loaded <script src="bower_components/angular-easyfb/angular-easyfb.js"></script> in your index.html  ?

**Comment by vin-san** [comment]
Yes, the js file is loaded in index.html.
Can this problem be linked to ng-Route ?

**Comment by vnctaing** [comment]
Try to inject correctly ezfbProvider in `.config(['$routeProvider','$locationProvider', 'ezfbProvider', function($routeProvider, $locationProvider, ezfbProvider)`  ?

**Comment by vin-san** [comment]
I found it. `ezfbProvider.setInitParams` was declared ouside the config function…
Sorry for that and many thanks for all your help & advices.

**Comment by pc035860** [comment]
@vin-san no problem!  Thank you @vnctaing !
