### ISSUE TITLE
"Main" field in package.json is wrong

### ISSUE THREAD

**Issue by dodo0822** [pc035860/angular-easyfb#63]
Hi,

The "main" field in ```package.json``` should be ```src/angular-easyfb.js``` instead of ```index.js```. The wrong value makes webpack fail to build if I use ```require('angular-easyfb');``` because it can't find ```index.js```.

**Comment by pc035860** [comment]
PR #62 should fix this. Thanks for the report.

**Comment by pc035860** [comment]
Just published v1.4.2. Issue close.
