### ISSUE TITLE
Get ezfb to work with import

### ISSUE THREAD

**Issue by jwanglof** [pc035860/angular-easyfb#71]
So I'm trying to migrate my Angular-app to a more CommonJS/ES6 standard and trying to use ezfb with imports, like this:

    import ezfb from 'angular-easyfb';
    angular.module('myAngularApp', [ezfb]);

But I keep getting `Error: [$injector:modulerr] Failed to instantiate module myAngularApp due to:
[$injector:modulerr] Failed to instantiate module {} due to:
[ng:areq] Argument 'module' is not a function, got Object`

When I try this instead:

    import ezfb from 'angular-easyfb';
    angular.module('myAngularApp', ['ezfb']);

I get this: `Error: [$injector:unpr] Unknown provider: ezfbProvider <- ezfb <- MyFactory`

Any ideas? =)

**Comment by pc035860** [comment]
Hi @jwanglof 

This module currently doesn't support CommonJS, AMD or ES6 module.

If you're using webpack, you can try serving `angular` with  [ProvidePlugin](https://webpack.github.io/docs/list-of-plugins.html#provideplugin) and simply import the module without specifying any imports.

webpack.config.js
```js
module.exports = {
  ...,
  plugins: [
    new webpack.ProvidePlugin({
      angular: 'angular'
    })
  ],
  ...,
};
```

app.js
```js
import 'angular-easyfb';
angular.module('myAngularApp', ['ezfb']);
```

I haven't try this myself before, but this is the way how jQuery plugins get imported.

**Comment by jwanglof** [comment]
I'm using Brunch, but thanks for the tip! =)
I ended up using `browserif-shim` instead, with this shim:

    ...,
    "browserify-shim": {
      "angular": {
        "exports": "angular"
      },
      "angular-easyfb": {
        "exports": "angular.module('ezfb').name"
      }
    },
    ...

Not sure if the `angular`-shim is needed though =)
