### ISSUE TITLE
Login Button doesn't work

### ISSUE THREAD

**Issue by monossido** [pc035860/angular-easyfb#83]
Suddenly the facebook login button in my angular js app started to not working.
I didn't thought about easyfb until I tried the demo here

http://plnkr.co/edit/z8751z?p=preview

also in the demo the button doesn't work
what's going on?

Thank you.

**Comment by pc035860** [comment]
The demo still works for me. Did you see any error message from Facebook?

**Comment by monossido** [comment]
Omg, now both buttons are working.
Sorry

**Comment by mabdelfattah** [comment]
I've the same problem, it is happening randomly!
